---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keight-apiserver-demo-apiserver
  namespace: default
  labels:
    api: keight-apiserver-demo
    apiserver: "true"
spec:
  selector:
    matchLabels:
      api: keight-apiserver-demo
      apiserver: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: keight-apiserver-demo
        apiserver: "true"
    spec:
      containers:
      - name: apiserver
        image: hisunyh/keight-apiserver-demo:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: apiserver-certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        command:
        - "./apiserver"
        args:
        - "--etcd-servers=http://kine-svc:2379"
        - "--tls-cert-file=/apiserver.local.config/certificates/tls.crt"
        - "--tls-private-key-file=/apiserver.local.config/certificates/tls.key"
        - "--audit-log-path=-"
        - "--feature-gates=APIPriorityAndFairness=false"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: keight-apiserver-demo
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: keight-apiserver-demo
  namespace: default
  labels:
    api: keight-apiserver-demo
    apiserver: "true"
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR0akNDQXA2Z0F3SUJBZ0lJVnVhZVBLWWVldEl3RFFZSktvWklodmNOQVFFTEJRQXdkVEVMTUFrR0ExVUUKQmhNQ2RXNHhDekFKQmdOVkJBZ01Bbk4wTVFvd0NBWURWUVFIREFGc01Rb3dDQVlEVlFRS0RBRnZNUXN3Q1FZRApWUVFMREFKdmRURTBNRElHQTFVRUF3d3JhMlZwWjJoMExXRndhWE5sY25abGNpMWtaVzF2TFdObGNuUnBabWxqCllYUmxMV0YxZEdodmNtbDBlVEFlRncweU16QTRNRFF4TURFNE1UVmFGdzB6TXpBNE1ERXhNREU0TVRaYU1Dd3gKS2pBb0JnTlZCQU1USVd0bGFXZG9kQzFoY0dselpYSjJaWEl0WkdWdGJ5NWtaV1poZFd4MExuTjJZekNDQVNJdwpEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWN1eDhpQnN0QTdYZ0VJQ095U2tGcFVVc1pZClVFMTltNEFBdXVOUGRoTER3MUVlUmhDdjRXaFRBOUx2a3d5L3JzL0gvbm9oOVlYUHo1b1YxeDU3c3dsNXdCdHIKNmFGVDhuWlFZZGR0RWp1S3g2V3NqYkF6UUFrM3hMeGRBTGFBMW44YUNNUmNZT3Z1MmVKQlFwbzV6aDdZVVZ3Swp2ZzlYeWF2NDB5WEV2QThNZEJtVU5qNHI5cGV4V2EyTEZ2Zm5aa1lYcVZUZy9nbCtZQnVRSTFTdXpBMFBDVXFvCkI0R1orQlNsVlIxWmZCMml2WElsSEgxRUZRbndvekZGVXlXMXBBYVdYWCtEdGYycUpHME5NaXhISHAyN0VFSDUKYkNpcGRGMFQ3NjdvMkdLM0VYd3VhVGxreC9uTWZQME9xK0R3eG1yZHYveDhvM25BcHZKMi9WWkVmYWNDQXdFQQpBYU9Ca2pDQmp6QU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHCkFRVUZCd01DTUI4R0ExVWRJd1FZTUJhQUZQc0tCZWNjUWdkTERydUVpRzZ0Zytva00ycmZNRDBHQTFVZEVRUTIKTURTQ0NXeHZZMkZzYUc5emRJSWhhMlZwWjJoMExXRndhWE5sY25abGNpMWtaVzF2TG1SbFptRjFiSFF1YzNaagpod1IvQUFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0JzNXRBdEJZaWlNWVU4Q3ZoL0plSit5aEJxUDRpClBaTUQ1V1pMT1FuZjBucWM4aXNhUGh0SGYvREphUzBmMHo5UWJ2YzBIVFBUT09nem1Nb29hQ0dmM2ZXQUJXMlYKOGlLMFA0U3hUOXNDVTFsSnUvRlE1bmM5QXlDMTVpVk1pNEJjVEdqTGdxMXRWQnRQbWY0b2Q4NVNtSGQ5VFJsRgpnQ2YwSk94NEZJV2prS0lGQS9xQzF4VGNvc2tSQ04rTDZBT1A0T0xLS0UxZy9CTzl5L3hIZlNNelBFZXVjS3JPCnRFSm9jSHhiTUFUNXBLUzVOdkVjOTZQdisvRjl1MVo4ejFnUEFDSFlaaFVsOVk5NUtXdmdRVnY5WDI5ZjZpdHEKdk96ZitoZzlKOEN2bStoMzA0cDl2UnZvNm5jZllHMWpVVEx2VXFQOHZlQTFseTAzNEVvZGdhNUsKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBeHk3SHlJR3kwRHRlQVFnSTdKS1FXbFJTeGxoUVRYMmJnQUM2NDA5MkVzUERVUjVHCkVLL2hhRk1EMHUrVERMK3V6OGYrZWlIMWhjL1BtaFhYSG51ekNYbkFHMnZwb1ZQeWRsQmgxMjBTTzRySHBheU4Kc0ROQUNUZkV2RjBBdG9EV2Z4b0l4RnhnNis3WjRrRkNtam5PSHRoUlhBcStEMWZKcS9qVEpjUzhEd3gwR1pRMgpQaXYybDdGWnJZc1c5K2RtUmhlcFZPRCtDWDVnRzVBalZLN01EUThKU3FnSGdabjRGS1ZWSFZsOEhhSzljaVVjCmZVUVZDZkNqTVVWVEpiV2tCcFpkZjRPMS9hb2tiUTB5TEVjZW5ic1FRZmxzS0tsMFhSUHZydWpZWXJjUmZDNXAKT1dUSCtjeDgvUTZyNFBER2F0Mi8vSHlqZWNDbThuYjlWa1I5cHdJREFRQUJBb0lCQVFDTXE5aERIbjU0SEFXRwordks2aWNSVFYweGljb3E4UDZLcjQxZ2FJOHVDOHlrbFNCazV2YzJYRFZJZERrQXZkOHp4U0JETWx1RTgwUWlRCmpTNHhoREZzMXNTN1dScFdhdUJKZVBtdzJJSlE5UEdOYTNGaDZNQW9BbS82akVCdHBFNVkwNzB2V1FMR2ZoajUKZHhlZnJvV0pPVU0wbXcyaDdtRXJDSCt2SStPaFIrMGFleUtORmU1dEtld0NZT1gzZTR4YUdia3RmaVI5SW5NSApXRVNSbTBVNWEwcTNTam1tK0pHWkxtbTZFT01QdmttL0tReCt4L0cxcjMxS29pRlZEQW5wSzRTc0tKZE0zN0FGCjFLYkR0YWxLdDh5Vy9EK2VrYXNTR290Zk1Nc3VJaUxkdFFyZGdVNWFZMHhiZ2NrNEVqN3JtZFByaHpubFg2eXUKbzFoeFRSY1pBb0dCQU02YStRS1dnSHZ6L1ZaVXRMRlZ2TG1iOWV3K2JvVVVHS3AwYnpDMkNzN21tcXlzamJJOQplZ0lNSlZzeWNzZWtnYVM2b0orV3UxUG5YVk5rZFFrT1VlUkh6VXpWeW92VWJoNnFHTDVMeW92MHRXSnJ4WHhqCjVrbGRTMXJaYVFNbmIxSHA4b0lrUmZYK24zYy9kbitpOWt3dzVDZ1FJMDF4MUVCa0xSQjQ1dWZUQW9HQkFQYk4KZzliQUdPMmR4eEQwLzdOQ0c1dnNvVVoyMXJvQnJTVjcrQlI4Zy9pY2E5cThrcnlUMzlmWXZ1RlhSdGxJbnZURQp6R2lpMVR2VEd3d0FRVEZneTFyZ1RQT1NiT3h0ZFhOditkSGxRSDdtenRPeEZlZmRxcW1OMTdIZzR2djFyVkwvCjRyVVlwZS9FV3VMdmQxa2daWFp3U09ZYlZXVkxCWkpYdFk2ZEh1SmRBb0dBQytUMkl3VUJIcUc4V3dVRFpoWTIKaUVVSFVuT0JyMTJwMGQ1a0xGeStvSXk4S09iQ1BabTJkWG0zaU5tTnJCcTNjQUZpaisyQW1XTC9oM2FJR2w1ZApycFBIcVAzQjdHenRiZ3lDNGluQTNtL1hKWFJvNlRGako2UWNXMzJhd3hpNUd2RXFDZjRHblJQc29GUGlBWlVqCk10MjV0T2pBNzR0M0djSHFxa0Vib2dzQ2dZQS9lRDdOZlgxcnJrWEJjS0JKbzFpaVVzcHU2cVR5RlBoSVNZZFYKRFdpTENQOGJzNTh3Ni82RzdmQzQxczhibGZkN0R4bGFWM1hxK3JGYjlyek5UQTFBQTZzR2dNT09VZUFBbmUxcgpNei9RNHQ2UnhsclIxRW5OYlBMcGhlSVoxZWFMRDg5bnJ6ME5XanZkWEtRZXdad1dSMjRYN3pPWTV5QTVzR0M2Cm1tR1U2UUtCZ0UyOWplaFVLdG1PeitRVVhTS1ZIZUZkai9pY3dVR29XTnF1bGQ2UyszbWN0YTdwNmliNXlnRWIKUUJaRUFoOHBWcU9iR094YjVldEhQMFBTUGs1SjRxUm5SQ3RtSlUxNkxTT0xrNUVhUTVrK0Y2VHgzYWsyOU9RLwpjTFQrT2R3Ym5IbGZiTlZIbHNDamZ1aklaLzdyVktPbkdxOS9pci9aZTJ1SjQ4YzI4OVMyCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: v1
kind: Service
metadata:
  name: keight-apiserver-demo
  namespace: default
  labels:
    api: keight-apiserver-demo
    apiserver: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    api: keight-apiserver-demo
    apiserver: "true"
