---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keight-apiserver-demo-controller
  namespace: default
  labels:
    api: keight-apiserver-demo
    controller: "true"
spec:
  selector:
    matchLabels:
      api: keight-apiserver-demo
      controller: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: keight-apiserver-demo
        controller: "true"
    spec:
      containers:
      - name: controller
        image: hisunyh/keight-apiserver-demo:latest
        imagePullPolicy: IfNotPresent
        command:
        - "./controller-manager"
        args:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 300Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: keight-apiserver-demo
