apiVersion: apps/v1
kind: Deployment
metadata:
  name: kine
  namespace: default
  labels:
    app: kine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kine
  template:
    metadata:
      labels:
        app: kine
    spec:
      containers:
        - name: kine
          image: rancher/kine:v0.10.2
          command:
            - kine
          args:
            - --endpoint=mysql://root:123456@tcp(mysql-svc:3306)/kine
          ports:
            - containerPort: 2379
              name: kine
---
apiVersion: v1
kind: Service
metadata:
  name: kine-svc
  namespace: default
spec:
  ports:
    - port: 2379
      targetPort: 2379
      protocol: TCP
      name: kine
  selector:
    app: kine