apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-scheduler-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sample-scheduler-crb
subjects:
  - kind: ServiceAccount
    name: sample-scheduler-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |

    apiVersion: kubescheduler.config.k8s.io/v1beta1
    #     clientConnection:
    #       acceptContentTypes: ""
    #       burst: 100
    #       contentType: application/vnd.kubernetes.protobuf
    #       kubeconfig: /etc/kubernetes/scheduler.conf
    #       qps: 50
    enableContentionProfiling: true
    enableProfiling: true
    healthzBindAddress: ""
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      leaseDuration: 15s
      renewDeadline: 10s
      resourceLock: endpointsleases
      resourceName: kube-scheduler
      resourceNamespace: kube-system
      retryPeriod: 2s
    metricsBindAddress: ""
    percentageOfNodesToScore: 0
    podInitialBackoffSeconds: 1
    podMaxBackoffSeconds: 10
    profiles:
    - pluginConfig:
      - args:
          favoriteColor: "#326CE5"
          favoriteNumber: 7
          thanksTo: "Kubernetes"
        name: sample-plugin
      schedulerName: sample-scheduler
      plugins:
        preFilter:
            enabled:
            - name: "sample-plugin"
        filter:
            enabled:
            - name: "sample-plugin"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-scheduler
  namespace: kube-system
  labels:
    component: sample-scheduler
spec:
  selector:
    matchLabels:
      component: sample-scheduler
  template:
    metadata:
      labels:
        component: sample-scheduler
    spec:
      serviceAccountName: sample-scheduler-sa
      priorityClassName: system-cluster-critical
      volumes:
        - name: scheduler-config
          configMap:
            name: scheduler-config
      containers:
        - name: scheduler
          image: hisunyh/scheduler-sample:v0.0.1
          imagePullPolicy: Always
          args:
            - --config=/etc/kubernetes/scheduler-config.yaml
            - --v=3
          volumeMounts:
            - name: scheduler-config
              mountPath: /etc/kubernetes