apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-webhook-sample-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admission-webhook-sample-role
rules:
- verbs: ["*"]
  resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
  apiGroups: ["admissionregistration.k8s.io"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admission-webhook-sample-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admission-webhook-sample-role
subjects:
- kind: ServiceAccount
  name: admission-webhook-sample-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-webhook-sample
  labels:
    app: admission-webhook-sample
spec:
  selector:
    matchLabels:
      app: admission-webhook-sample
  template:
    metadata:
      labels:
        app: admission-webhook-sample
    spec:
        serviceAccountName: admission-webhook-sample-sa
        initContainers:
        - image: hisunyh/admission-webhook-sample-tls:v0.0.1
          imagePullPolicy: Always
          name: webhook-init
          volumeMounts:
            - mountPath: /etc/webhook/certs
              name: webhook-certs
          env:
            - name: MUTATE_CONFIG
              value: admission-webhook-sample-mutate
            - name: VALIDATE_CONFIG
              value: admission-webhook-sample
            - name: WEBHOOK_SERVICE
              value: admission-webhook-sample
            - name: WEBHOOK_NAMESPACE
              value:  default
            - name: VALIDATE_PATH
              value: /validate
            - name: MUTATE_PATH
              value: /mutate
        containers:
        - name: whitelist
          image: hisunyh/admission-webhook-sample:v0.0.1
          imagePullPolicy: Always
          env:
          - name: WHITELIST_REGISTRIES
            value: "docker.io,gcr.io"
          ports:
          - containerPort: 443
          volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook/certs
            readOnly: true
        volumes:
        - name: webhook-certs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: admission-webhook-sample
  labels:
    app: admission-webhook-sample
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: admission-webhook-sample