apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission-webhook-sample
webhooks:
- name: easy.sunnyh.admission-webhook-sample
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
  clientConfig:
    service:
      namespace: default
      name: admission-webhook-sample
      path: "/validate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtakNDQW9LZ0F3SUJBZ0lVY3hSdjd6TXlkYlA1ZjhvQjBRUnN2REFCVmpFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEl4TVRBeU5UQTRORGt3TUZvWERUSTJNVEF5TkRBNE5Ea3dNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMXNFNzJUSGhHb2ozcUR1Vk9nY2MKQiswM0lQc1JjNStCNUhIRWMxSFBrdFp0M2VOZzFXRmUzTlFLSEpYMlNUb2xBY0lwMmdibGN0TU51dGpmYXZNYQpaZUxuSjh3QU8vYkhQbXJhRmZJb0FqTktQbWlJWStWQjA0YzIrMzA5WHY4WHBaWSs1VUR2OVB4MXpTeWVIYlBUCkJYOG05MiswQnYyZHBpSnFMcC85OGRSbi9xTW15aUx1NXpETDh3SEQ3MlBtZHpjYnJvSjFDQ2U1bm1wdVo4aFQKSmI0SzFTM3Z5TEVwNWhhL2VJYXIzQ3RMVnhYamhiZ0hhOW9qSmJvcVl3MC9DdUExS3duRURPRkxyYzRIRlN0cAo5U3FvYWZORlM3d2lsMkp2Nk9NVzNGenM5TWNIS0g2MGhiNWdOTGJuRTlLKzg2T1N3WEp6ZXZhZUhNMWt6d3NECnZ3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlYKSFE0RUZnUVVzdU1TZmU3S2FsMjJNU1g3UWkwZXIxc1BISzh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUVYUgp1MW9qeGtrTDFHLzZ0V1hyY2lOK0FYNDNFWWg1bEp0eUpDa20rMHJnL1I0aGd3ejZGZDRxU0dVMzR2ZFFpOU12Cm9Nb2QyYzZqVEphTDZsQXpHT3VsREltTjJrRkFmVktGRDZ0cTNQN29wR0JRVDQ2bG8vcDBwTnRTM0FJN0VHeVYKa3UxWGhZajdpT0xSbm5weHdXTFhCMStDb3NkZE1EYytSQVQ2UEIwZ3JLOXZEQlRBSWx6dllNZDJqdTArZjQrYwp4OFpISmJCSmdFYnd3cElUN3BRZDVvMmxIbzlaVytDdkFvTnhxZHJFUHFDTENIWUpmc1JIczJ5MXZaaGpXRjVJCkZhSW8wL0dmRlIyZHQ5S1lRcUpGM1pITGVjWWRRQmZJWlN1dEYwRlJjclNydzRNWkl5d0pJakpic1FiUEV5Q24KL2NKNGdBTDZsTUFtdmoyOFBHQT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  admissionReviewVersions: ["v1"]
  sideEffects: None
